name: 'kube-linter'
description: 'Scan directory with kube-linter'
inputs:
  directory:
    description: 'Directory to scan '
    required: true
  config:
    description: 'Path to config file'
    required: false
  outputFile:
    description: 'Path to sarif output of scan, note raw output will be in a file called kubelinter.raw-output'
    required: false 
outputs:
  lint-txt:
    description: 'Output from linting'
    value: ${{ steps.lint.outputs.lint-txt }}
runs:
  using: "composite"
  steps:
    - name: Download latest kube-linter
      run: |
        LOCATION=$(curl -s https://api.github.com/repos/stackrox/kube-linter/releases/latest \
        | grep "tag_name" \
        | awk '{print "https://github.com/stackrox/kube-linter/releases/download/" substr($2, 2, length($2)-3) "/kube-linter-linux.tar.gz"}')
        curl -s -L -o kube-linter-linux.tar.gz $LOCATION
        tar -xf kube-linter-linux.tar.gz -C "${GITHUB_WORKSPACE}/"
      shell: bash
    - id: lint
      run: |
        cd "${GITHUB_WORKSPACE}"
        if [ -z ${{ inputs.config }} ]; then
          export CONFIG=""
        else
          export CONFIG="--config ${{ inputs.config }}"
        fi
        ./kube-linter $CONFIG lint ${{ inputs.directory }}  2>&1 >/dev/null | tee kubelinter.raw-output || true
        if [ -z ${{ inputs.outputFile }} ]; then
          cat kubelinter.raw-output
        else
          cat kubelinter.raw-output
          curl -s -L -o https://raw.githubusercontent.com/jduimovich/kubelinter-sarif-poc/main/kubelinter2sarif.js
          node kubelinter2sarif kubelinter.raw-output ${{ inputs.outputFile }}
        fi
      shell: bash

